name: Build

on: [push, release, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
        libsemigroups_version: [ '2.0.3' ]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.2.2

      - name: Build wheels
        env:
          CIBW_BEFORE_ALL_MACOS: > 
            curl -L -O https://github.com/libsemigroups/libsemigroups/releases/download/v${{ matrix.libsemigroups_version }}/libsemigroups-${{ matrix.libsemigroups_version }}.tar.gz &&
            tar -xf libsemigroups-${{ matrix.libsemigroups_version }}.tar.gz && 
            rm -f libsemigroups-${{ matrix.libsemigroups_version }}.tar.gz && 
            cd libsemigroups-${{ matrix.libsemigroups_version }} &&
            ./configure --disable-hpcombi &&
            make -j$(sysctl -n hw.ncpu) && make install 
          CIBW_BEFORE_ALL_LINUX: > 
            curl -L -O https://github.com/libsemigroups/libsemigroups/releases/download/v${{ matrix.libsemigroups_version }}/libsemigroups-${{ matrix.libsemigroups_version }}.tar.gz &&
            tar -xf libsemigroups-${{ matrix.libsemigroups_version }}.tar.gz && 
            rm -f libsemigroups-${{ matrix.libsemigroups_version }}.tar.gz && 
            cd libsemigroups-${{ matrix.libsemigroups_version }} &&
            ./configure --prefix=/usr --disable-hpcombi &&
            make -j$(nproc) && make install 
          CIBW_ENVIRONMENT_LINUX: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig
          CIBW_ARCHS_MACOS: x86_64 arm64 

        run: python -m cibuildwheel --output-dir wheelhouse 
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
